# Generated by Django 4.0.5 on 2022-07-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginSignup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.BigAutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=30)),
                ('productCategory', models.CharField(max_length=30)),
                ('productPrice', models.IntegerField()),
                ('warrantInMonths', models.IntegerField(default=0)),
                ('manufacturerDetails', models.CharField(max_length=200)),
                ('productDescription', models.TextField()),
                ('productImage', models.ImageField(upload_to='ProductImages/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginSignup.users')),
            ],
        ),
    ]
