# Generated by Django 4.0.5 on 2022-07-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0006_alter_users_walletbalance'),
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.BigAutoField(primary_key=True, serialize=False)),
                ('productQty', models.IntegerField(default=1)),
                ('addedToCartOn', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginSignup.users')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.products')),
            ],
        ),
    ]
