# Generated by Django 4.0.5 on 2022-07-06 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='addedToCartOn',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
