# Generated by Django 4.0.5 on 2022-07-18 06:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0006_alter_users_walletbalance'),
        ('myshop', '0003_alter_cart_addedtocarton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.BigAutoField(primary_key=True, serialize=False)),
                ('orderedOn', models.DateTimeField(default=datetime.datetime.now)),
                ('totalBillAmount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginSignup.users')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.orders'),
        ),
    ]
