# Generated by Django 4.0.5 on 2022-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_orders_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='totalBillAmount',
            field=models.FloatField(),
        ),
    ]
