# Generated by Django 4.0.5 on 2022-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_orders_estimateddeliverydate_orders_isorderdelivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('tagName', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(null=True, to='myshop.producttags'),
        ),
    ]
