# Generated by Django 4.0.5 on 2022-07-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_producttags_products_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='isRecommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='recommendationAmount',
            field=models.FloatField(default=0),
        ),
    ]
