# Generated by Django 4.0.5 on 2022-07-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_alter_orders_estimateddeliverydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyShopCenters',
            fields=[
                ('centerId', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipCode', models.CharField(max_length=10)),
            ],
        ),
    ]
