# Generated by Django 4.0.5 on 2022-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_myshopcenters'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deliveryCharges',
            field=models.IntegerField(default=0),
        ),
    ]
