# Generated by Django 4.0.5 on 2022-08-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_orders_deliverycharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cashbackRewarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='shopyCoinsRewarded',
            field=models.IntegerField(default=0),
        ),
    ]
