# Generated by Django 4.0.5 on 2022-08-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_orders_cashbackrewarded_orders_shopycoinsrewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='crownSymbol',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='orders',
            name='deliveryDiscount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='orderDiscount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cashbackRewarded',
            field=models.FloatField(default=0),
        ),
    ]
