# Generated by Django 4.0.5 on 2022-07-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userProfileImage',
            field=models.ImageField(default='noProfileImage.png', upload_to='UserProfileImages/'),
        ),
    ]
