# Generated by Django 4.0.5 on 2022-07-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0002_users_userprofileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userProfileImage',
            field=models.ImageField(default='UserProfileImages/noProfileImage.png', upload_to='UserProfileImages/'),
        ),
    ]
