# Generated by Django 4.0.5 on 2022-07-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0003_alter_users_userprofileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fullName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
