# Generated by Django 4.0.5 on 2022-07-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0004_users_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='addressLine',
        ),
    ]
