# Generated by Django 4.0.5 on 2022-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0005_rename_address_address_addressline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='walletBalance',
            field=models.FloatField(default=0),
        ),
    ]
