# Generated by Django 4.0.5 on 2022-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0007_users_usertype_premiumusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='shopyCoins',
            field=models.IntegerField(default=0),
        ),
    ]
